# Pull the latest base image
FROM node:alpine
# set working directory
WORKDIR /react-app
# add `/react-app/node_modules/.bin` to $PATH
ENV PATH /react-app/node_modules/.bin:$PATH
# Copy package.json to /react-app
COPY package.json ./
# Copy package-lock.json to /react-app
COPY package-lock.json ./
# Install dependencies
RUN npm i
# add app
COPY . ./
# start app
CMD ["npm", "start"]   
